name: drone_3d_model
description: "A new Flutter project for viewing OpenDroneMap 3D models."

publish_to: 'none' # Do not publish this package

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For selecting files/directories
  file_selector: ^1.0.3

  # For getting common file system paths (like application documents)
  path_provider: ^2.1.3 # ADD THIS LINE

  # For 3D model display (GLB format)
  model_viewer_plus: ^1.9.3

  # For path manipulation (joining paths, getting file extensions, etc.)
  path: ^1.9.0

  webview_windows: ^0.2.1

  # Standard Flutter icons (optional, if you use them)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/run_odm.bat
    # If you have any assets like default images or other files you want to bundle,
    # list them here. For ODM outputs, the app will read directly from the file system,
    # so you typically don't need to list actual 3D models here.
    # - assets/ # Example: if you had a folder called 'assets'
    # - assets/run_odm.bat # Example: if you bundled this specific file